apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    something: AgCgOwdW9LQaJxmPh6MfzOzokGWi3N8iHxerM3z5vdat/cDGFXnPRbconHNW+gL0m/Yjs2VN8F3JFWfxf1k9zKsHhxqYcbXcIbCL0UE6nYMmzpkDo0RlTp2b0ehS/yQH3r4aUTxv4RFKItI3KXp8ffzVuTsaaMGxKCJl/zio+BorDkoIi0H6mVpddjx5mJlzuPanKnldnH9pVHMRDs7Xc0WJAzCHsPmEDm/zY2Rox0hAj0R9Hrk8MAnZ3q86pkJTMoMsd8AOaHxxlUFbSGzqBNPRLGHk7ICVa7Lz+VxcTmhpi21Sdlo2qsVylsQNdFjsD16PUxq8edpOdwuXvkAuVUowtLo27wGeHJiY3JDrXi+F1qXmSImM1OHDrrOlQLY7ZNSGKctunolA5iy1GYoaeuTSS69LCMpHZnfD8H1i9Y3B0NB2VMKwAtF8dll88mGkYlKR+LlUUe0aEuoTc0n2r6/HLEWw4pkiU2B7gIfe/yTHl2XI0eR8yne8vwvybP3AvjKrBviq+E2/OJNtjSKGrsqmDDu7z7Xx4V8FqQ5MQfDj1kumigtYfjEj9L2zb/oMDe+a/pz+cS16YK7dCQGe+Iy9ajafPQ5j35oKvL9RnN6uVSI8vvrGMcXtJMoJ1mB92OVwO3cKCHtWXYZJjAJbbDO5tAk+yDrSiGll+MxooJ0Wj9R+frkJF42ElfQLGgpKa0BjeznGZiv54vUrP0uAY+UBUqxX3A==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
status: {}

