---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  something: YWJhY2F0ZSBzZWNyZXRv
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: genv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: genv
    spec:
      containers:
      - name: genv
        image: whothey/genv:1.0
        env:
          - name: PORT
            value: 3000
          - name: SECRET_ENV
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: something
        ports:
        - containerPort: 3000
